### ISSUE TITLE
Is timeseries fetch fragile to handling a lot of sites?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizstorm-GIF#103]
I was getting NWIS 503's with minimal gage filtering, and ultimately punted so I could get through the error w/ 
```r
sites_info_subset <- sites_info %>%
    # only include sites with large drainage areas
    filter(drain_area_va > quantile(drain_area_va, 0.75, na.rm=TRUE)) %>%
    head(10)
```
in `filter_sites_custom()` to reduce the number of sites we ultimately fetch IV data for. 
I think normally we'd do chunks of sites w/ rbinds to combine them.

**Comment by aappling-usgs** [comment]
I thought 503 meant service unavailable rather than bad query? But it's all a mystery, and it does sound like you were able to successfully download a smaller list, huh? With WQP last week we were getting some combo of 400 somewhere and 404 somewhere else, which they were able to fix by re-upping the WAF query size limit. I agree that breaking site lists into chunks generally seems to work. Alternatively, for such small time windows, maybe we'd be able to make requests as whole states or HUCs instead, (But I forget how NWIS works fastest - does subsetting time make it better or worse?)

**Comment by jread-usgs** [comment]
Seems this was a short-lived NWIS issue (I think). Closing for now.
