### ISSUE TITLE
pipeline for precip

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#4]
code is needed to fetch precip data, calculate cumulative precip, and do any other munging needed along the way

* precip data has come from at least 2 different sources for us in the past. data might come from www.srh.noaa.gov/data/ridge2/Precip/qpehourlyshape (maria) or GDP (most others, e.g., https://github.com/USGS-VIZLAB/hurricane-harvey/blob/master/scripts/fetch/fetchPrecip.R, https://github.com/USGS-VIZLAB/hurricane-irma/blob/master/scripts/fetch/fetchPrecip_cells.R). offer both (all?) in this template, to be flexible about the location of future storms.

* in past vizzies we've simplified the precip to county-level or large-grid-cell-level polygons. because this vizzy will use a raster/GIF format, such simplification is not needed here.

* it may be possible to simplify the precip-fetching code using sf and other insights; see https://github.com/USGS-VIZLAB/how-gdp/blob/master/scripts/fetch/fetch_utils.R#L14-L49 for our most recent iteration on this

**Comment by dblodgett-usgs** [comment]
There are a number of ways we could go with this. I just started working on the most direct use of the StageIV data possible. We have precip cells that lay out in a curvilinear grid like this:
![screen shot 2018-07-09 at 1 25 09 pm](https://user-images.githubusercontent.com/1492803/42468972-f70ca2d4-837b-11e8-9319-05e459a3558b.png)

In the past, we've generated a cell layout that we want for visualization and used geoknife to do the resampling. I think the premise here is that we will use this full precip cell resolution? 

Because it is on a curvilinear grid, we do have to work with it as point data -- which is fine as long as we can adjust the pch/cex of the points such that they completely overlap.

Question: Should I continue to pursue this approach? I will end up with a big-ol tidy data.frame (id, point location) of spatial information and an accompanying even bigger tidy data.frame with precip value data (id, time, value).

**Comment by jread-usgs** [comment]
Blodgett - interesting challenge. seems we'd end up tweaking cex and pch a lot if we went that route. Can you turn it into a grid of polygons?

**Comment by aappling-usgs** [comment]
`st_voronoi`? https://stackoverflow.com/questions/45719790/create-voronoi-polygon-with-simple-feature-in-r

**Comment by dblodgett-usgs** [comment]
Yes. I can pass along polygons instead of points.

**Comment by dblodgett-usgs** [comment]
Yes?
![screen shot 2018-07-09 at 2 52 55 pm](https://user-images.githubusercontent.com/1492803/42472684-d41d4330-8387-11e8-9dd1-e407f625416b.png)
This was helpful. https://github.com/r-spatial/sf/issues/474

**Comment by dblodgett-usgs** [comment]
OK, so my plan is to implement a process step that takes what's been fetched and returns a list of raster images that emulate the pixels of our gif. I can use the view_polygon as the domain of the raster, but what should I do about the resolution? e.g. where do I get the information to generate a cell count in x and y?

**Comment by dblodgett-usgs** [comment]
I'm wrapping this up. We may need to iterate on things a bit. I ended up using the fasterize package to convert sf polygons to raster rather than going full on GDP style spatial intersection. What this means is that we only have access to "max", "min", "any" type statistics when transferring values from the curvilinear grid to the raster grid. For now, I just chose max, but we can experiment with changing it if we want. For now, it's hard coded, but easy to change.

**Comment by aappling-usgs** [comment]
"max" sounds like it could lead to some noticeably flawed cumulative precip estimates. (are you already computing cumulative, or are these precip totals within each timestep?) what is "any"?

**Comment by dblodgett-usgs** [comment]
Shoot. I hadn't thought about the cumulative being applied after the resampling. I'll accumulate before converting to raster.
 
I'm not sure what the "any" is. Sounds sloppy.

**Comment by dblodgett-usgs** [comment]
OK, I just added a:
```
    group_by(id) %>%
    arrange(time_id, .by_group = TRUE) %>%
    mutate(precip = cumsum(precip)) %>%
    ungroup()
```
Update to my PR is coming once this rebuilds.
