### ISSUE TITLE
try a new storm

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm-GIF#82]
We should make a new google drive folder for this.

Find out what it takes to launch a new storm from scratch.

Change `fetch_streamorder` to be higher (e.g., 4th order) for faster query.

Irma would make it faster too.

**Comment by jread-usgs** [comment]
So far:

- change storm details in viz_config.yml
- create new shared gdrive folder
- change `folder` lib.yml
- remove `.remake` and `build/status` dirs
- delete contents in `6_visualize/tmp`
- change the sites in `filter_sites_custom` (this seems painfully manual right now)

But currently still running into issues that I don't think should pop up if we have everything connected:
```
* Error in prep_spark_funs_data(storm_data, site_data, timestep_ind, spark_config, : no stage data for dateTime<=2017-09-10 16:00:00 and site=03431091; debug with scmake("6_visualize/tmp/gif_frame_a_20170910_16.png", "6_storm_gif_t...
* Error in     DateTime): no stage data for dateTime<=2017-09-10 16:00:00 and site=03431091; debug with scmake("6_visualize/tmp/gif_frame_a_20170910_16.png", "6_storm_gif_tasks.yml")
```

**Comment by aappling-usgs** [comment]
Can we change "change `folder` lib.yml" to "update gdrive folder ID in lib/cfg/gd_config.yml"? I'd like to delete lib.yml, in fact (#95).

Interesting that you had to delete contents of 6_visualize/tmp - they weren't getting overwritten as needed?

Is it possible to use a really bare-bones version of filter_sites_custom at first, then later add in the parts that are painfully manual once we've had a chance to look at the output for all sites?

**Comment by jread-usgs** [comment]
yeah, I think we can get closer to an automated selection of gages that we can further pare down manually. We've used a buffered area near the storm track in the past, or specified a polygon ring as a vector...

**Comment by jread-usgs** [comment]
I added a manual state filter to the viz_config that includes a vector of states to use. I would suggest we use that instead of all of the states that appear in the view (which can be many). For this Irma re-build, I started w/ FL, GA, and AL. 

It is challenging to iterate on getting the view right, since changing it re-downloads all of the precip and river data. Ideally, I'd want to be able to see a png frame with just the geometries and storm-track (no rivers, precip, gages, or sparks) so we can more quickly converge on image size and location of the viewbox. 

I _think_ this would be possible by adding another stage to the task table that no other stages depend on (so it wouldn't be built) and it could include a subset of the plot functions. Calling something like 
```r
scmake('6_visualize/.test_cache/gif_TEST_frame_a_20170908_03.png', remake_file='6_storm_gif_tasks.yml', force = TRUE)
``` 
directly would be the way you could preview a frame w/o all of the other goodies (and therefore, hopefully, w/o triggering a rebuild of all of the other goodies).

**Comment by jread-usgs** [comment]
Piggybacking ☝️ and since that plotting would be diagnostic only, perhaps the function should also include plotting the `bbox` specified in the `viz_config.yml`. Because the bounds of the figure are ultimately a combination of the `height`, `width`, _and_ `bbox`, it might be helpful to know which coords in `bbox` you need to bump to get the view you want. Plotting the bbox seems like the most straightforward way to do that. 

I think I am going to try this out and report back

**Comment by jread-usgs** [comment]
I'm not yet really thinking about that part of this task...getting through the plumbing and documenting the challenges for getting a workable gif first. My gut says a storm-specific branch (maybe even named `al112017-Irma` if it is a hurricane?) would work well in these cases, but I haven't considered the downsides of that at all at this point.

**Comment by jread-usgs** [comment]
altering the `bbox` and simply running `scmake('6_storm_gif_tasks.yml', '6_visualize.yml')` triggers a pretty extensive rebuild, ~and I'm not sure why.~ because it relies on `2_process/out/timesteps.rds.ind`, which is a product of the precip rasters

The result of adding a "test" frame to the task_remake is this: 
![gif_test_frame_a_20170908_03](https://user-images.githubusercontent.com/2349007/44218721-ea41ea00-a13f-11e8-940f-262c34f972ef.png)

The experimentation with this frame view is still pretty expensive - it involves the full `fetch_precip_values` and `process_precip_rasters`, which are both heavy (all other targets that feed into this are light). I can make it much faster (but still not "fast") by specifying something like
```yaml
dates:
  start: '2017-09-08 03:00:00
  end: '2017-09-08 03:00:00'
``` 
in the config, but see issue #96 (I put a small fix in for that on the branch I am working on).
