### ISSUE TITLE
handle gaps in gage data

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizstorm-GIF#86]
See comments in https://github.com/USGS-VIZLAB/vizstorm-GIF/issues/12#issuecomment-404565831 for criteria.

**Comment by lindsaycarr** [comment]
^ Hmmm had not considered that when I originally wrote this. It's written vaguely enough to include both, but I think MVP would be just the spark line

**Comment by aappling-usgs** [comment]
I like the idea of throwing an error if we have more than one gap - i worry about just ignoring the possibility but agree that it could be a pain to code for `n` gaps, so an error seems like a good compromise.

The code changes for gaps in hydrograph vs gage point will probably happen in quite different functions, but I think we need a plan for what to do with the gage point - I could reluctantly settle for leaving the gage unchanged, as @lindsaycarr is suggesting, but I would rather see the change on the map simultaneously. Open to further disagreement/discussion, though.

If changing both sparks and points is too big for one PR, then 2 PRs for this issue would be fine with me, but I'd prefer to see both tasks resolved, and at least today I'm OK with lumping those two tasks into this one GitHub issue rather than breaking them out.

**Comment by jread-usgs** [comment]
Yeah, I agree that I'd prefer both, to the point where we should consider the MVP to just manually filter out gages w/ gaps, but the thing we are shooting for is the Maria experience/styling.

**Comment by aappling-usgs** [comment]
Right now I seem to have things working for the sparklines (still need to do the site points) except I was still working on Harvey and the Drive might be corrupt because now my computer is trying to rebuild precip (which it can't. not a mac.). So I won't put in a PR quite yet, but here's what I could do before that rebuild got triggered:
![image](https://user-images.githubusercontent.com/12039957/44241201-59dfc580-a190-11e8-84b7-8a82158d45fb.png)

**Comment by jread-usgs** [comment]
Looking good! :+1: 
I am stuck on some NWIS 503s, so skipping out for the night. I wonder if it is worth tackling that precip build to work on windows? Or at least capture it in an issue.

**Comment by aappling-usgs** [comment]
It would certainly be useful if anybody could do the precip build. I just added #102 but also categorized it as a Could Do because I think our MVP should be a releasable viz.

**Comment by aappling-usgs** [comment]
Resolved by #106 and #114
